### ISSUE TITLE
Backend - Brainstom/Design User Database (US #1)

### ISSUE THREAD

**Issue by Maxwell-Lam** [benhmoore/SE-Project-Group-4#10]
Discuss all attributes of a user. 

Basic Attribute: 
1. First Name
2. Last Name
3. Username
4. Password
5. Account Money
6. Seller Status
7. Admin Status

Discuss possible relational keys between the item database. 

Marked As Complete Once:
1. Create a basic diagram to represent the OBJ of a user.
2. Understand the data link between the item and the user database. 
3. Create a basic diagram to represent Task 2.

**Comment by benhmoore** [comment]
This issue can be considered a part of [[User Story]] #1
