### ISSUE TITLE
Backend - Brainstorm/Design Merchandise OBJ

### ISSUE THREAD

**Issue by Maxwell-Lam** [benhmoore/SE-Project-Group-4#8]
Discuss what features/characteristics an item on sale should have. 

Minimum: 
1. Item Name
2. Price
3. Seller

Design representation in SQL database. 
Discuss the program structure for OBJ. 

Marked as Complete Once:
1. Create a basic diagram to represent the OBJ of merchandise.

**Comment by benhmoore** [comment]
This was completed as a team effort.
